### ISSUE TITLE
在使用旧版安卓/新版安卓媒体通知栏时出现问题

### ISSUE THREAD

**Issue by GDZJS** [HowieHChen/XiaomiHelper#12]
在使用旧版安卓/新版安卓媒体通知栏时出现问题
多次点击媒体通知栏的按钮会使系统界面卡死
并且长按重启会卡出原生电源选项
问题发生在:
小米13ultra 开发版24.3.18
小米pad6 pro开发版 1.0.4

**Comment by GDZJS** [comment]
目前测试是在通知栏或者锁屏 多次按一个按钮会导致 不管是下一曲 还是歌词 
条件：旧版安卓、波浪线进度条、自动反色、（不管是否显示全部按钮都会有这个问题）

**Comment by GDZJS** [comment]
该问题出现在2.5.0（未完全构建版本上）

**Comment by GDZJS** [comment]
以下是LSP日志：
[ 2024-03-28T19:10:03.149    10174: 21751: 21751 I/LSPosed-Bridge  ] Loading legacy module dev.lackluster.mihelper from /data/app/~~PtLE5vUIOrqcyzHHhuzy7A==/dev.lackluster.mihelper-qOVoBw-euPA7qGg7Y7U64g==/base.apk
[ 2024-03-28T19:10:03.167    10174: 21751: 21751 I/LSPosed-Bridge  ]   Loading class dev.lackluster.mihelper.hook.HookEntry_YukiHookXposedInit
[ 2024-03-28T19:10:29.643    10145: 23389: 23389 I/LSPosed-Bridge  ] Loading legacy module dev.lackluster.mihelper from /data/app/~~PtLE5vUIOrqcyzHHhuzy7A==/dev.lackluster.mihelper-qOVoBw-euPA7qGg7Y7U64g==/base.apk
[ 2024-03-28T19:10:29.652    10145: 23389: 23389 I/LSPosed-Bridge  ]   Loading class dev.lackluster.mihelper.hook.HookEntry_YukiHookXposedInit
[ 2024-03-28T19:10:30.595    10115: 23473: 23473 I/LSPosed-Bridge  ] Loading legacy module dev.lackluster.mihelper from /data/app/~~PtLE5vUIOrqcyzHHhuzy7A==/dev.lackluster.mihelper-qOVoBw-euPA7qGg7Y7U64g==/base.apk
[ 2024-03-28T19:10:30.603    10115: 23473: 23473 I/LSPosed-Bridge  ]   Loading class dev.lackluster.mihelper.hook.HookEntry_YukiHookXposedInit
[ 2024-03-28T19:10:32.083    10248: 23548: 23548 I/LSPosed-Bridge  ] Loading legacy module dev.lackluster.mihelper from /data/app/~~PtLE5vUIOrqcyzHHhuzy7A==/dev.lackluster.mihelper-qOVoBw-euPA7qGg7Y7U64g==/base.apk
[ 2024-03-28T19:10:32.090    10248: 23548: 23548 I/LSPosed-Bridge  ]   Loading class dev.lackluster.mihelper.hook.HookEntry_YukiHookXposedInit
[ 2024-03-28T19:10:40.122    10235: 23975: 23975 I/LSPosed-Bridge  ] Loading legacy module dev.lackluster.mihelper from /data/app/~~PtLE5vUIOrqcyzHHhuzy7A==/dev.lackluster.mihelper-qOVoBw-euPA7qGg7Y7U64g==/base.apk
[ 2024-03-28T19:10:40.135    10235: 23975: 23975 I/LSPosed-Bridge  ]   Loading class dev.lackluster.mihelper.hook.HookEntry_YukiHookXposedInit
[ 2024-03-28T19:10:41.228     1000: 24110: 24110 I/LSPosed-Bridge  ] Loading legacy module cn.lyric.getter from /data/app/~~ItDt-IHQsczwsLPiS6-fOw==/cn.lyric.getter-L3DAgRQMe2EESQUTdrbQ8w==/base.apk
[ 2024-03-28T19:10:41.390     1000: 24110: 24110 I/LSPosed-Bridge  ]   Loading class cn.lyric.getter.hook.MainHook
[ 2024-03-28T19:10:41.402     1000: 24110: 24110 I/LSPosed-Bridge  ] Loading legacy module cn.aodlyric.xiaowine from /data/app/~~n8HK7_61m7alzRsHQfuIsg==/cn.aodlyric.xiaowine-htj2OnwTpfRNRcfwUcAVmg==/base.apk
[ 2024-03-28T19:10:41.424     1000: 24110: 24110 I/LSPosed-Bridge  ]   Loading class cn.aodlyric.xiaowine.hook.MainHook
[ 2024-03-28T19:10:41.454     1000: 24110: 24110 I/LSPosed-Bridge  ] Loading legacy module statusbar.lyric from /data/app/~~0vXMibUqeJ90ay596fnB8Q==/statusbar.lyric-A6dMbZxOctiho9XvDfGWog==/base.apk
[ 2024-03-28T19:10:41.459     1000: 24110: 24110 I/LSPosed-Bridge  ]   Loading class statusbar.lyric.hook.MainHook
[ 2024-03-28T19:10:41.497     1000: 24110: 24110 I/LSPosed-Bridge  ] Loading legacy module dev.lackluster.mihelper from /data/app/~~PtLE5vUIOrqcyzHHhuzy7A==/dev.lackluster.mihelper-qOVoBw-euPA7qGg7Y7U64g==/base.apk
[ 2024-03-28T19:10:41.507     1000: 24110: 24110 I/LSPosed-Bridge  ]   Loading class dev.lackluster.mihelper.hook.HookEntry_YukiHookXposedInit
[ 2024-03-28T19:10:41.753     1000: 24110: 24110 D/LSPosed-Bridge  ] Inited hook: OOO8o〇o
[ 2024-03-28T19:10:43.835    10122: 24525: 24525 I/LSPosed-Bridge  ] Loading legacy module com.omarea.vtools from /data/app/~~hJaJegIvgU_dfRaoA_E0zA==/com.omarea.vtools-YxsOmfOUnEESbmdDBURO6w==/base.apk
[ 2024-03-28T19:10:43.865    10122: 24525: 24525 I/LSPosed-Bridge  ]   Loading class com.omarea.xposed.XposedInterface
[ 2024-03-28T19:10:43.947    10113: 24518: 24518 I/LSPosed-Bridge  ] Loading legacy module dev.lackluster.mihelper from /data/app/~~PtLE5vUIOrqcyzHHhuzy7A==/dev.lackluster.mihelper-qOVoBw-euPA7qGg7Y7U64g==/base.apk
[ 2024-03-28T19:10:43.987    10113: 24518: 24518 I/LSPosed-Bridge  ]   Loading class dev.lackluster.mihelper.hook.HookEntry_YukiHookXposedInit
[ 2024-03-28T19:10:56.303    10248: 25854: 25854 I/LSPosed-Bridge  ] Loading legacy module dev.lackluster.mihelper from /data/app/~~PtLE5vUIOrqcyzHHhuzy7A==/dev.lackluster.mihelper-qOVoBw-euPA7qGg7Y7U64g==/base.apk
[ 2024-03-28T19:10:56.310    10248: 25854: 25854 I/LSPosed-Bridge  ]   Loading class dev.lackluster.mihelper.hook.HookEntry_YukiHookXposedInit
[ 2024-03-28T19:10:59.944    10254: 26057: 26057 I/LSPosed-Bridge  ] Loading legacy module pansong291.xposed.quickenergy.repair from /data/app/~~q_sVbKZ4iv8WJxLTlvvZAA==/pansong291.xposed.quickenergy.repair-LkpXGjGjR5QixXexdLLk2Q==/base.apk
[ 2024-03-28T19:10:59.948    10254: 26057: 26057 I/LSPosed-Bridge  ]   Loading class pansong291.xposed.quickenergy.hook.XposedHook
[ 2024-03-28T19:11:00.294    10254: 26153: 26153 I/LSPosed-Bridge  ] Loading legacy module pansong291.xposed.quickenergy.repair from /data/app/~~q_sVbKZ4iv8WJxLTlvvZAA==/pansong291.xposed.quickenergy.repair-LkpXGjGjR5QixXexdLLk2Q==/base.apk
[ 2024-03-28T19:11:00.296    10254: 26153: 26153 I/LSPosed-Bridge  ]   Loading class pansong291.xposed.quickenergy.hook.XposedHook
[ 2024-03-28T19:11:31.481    10254: 27306: 27306 I/LSPosed-Bridge  ] Loading legacy module pansong291.xposed.quickenergy.repair from /data/app/~~q_sVbKZ4iv8WJxLTlvvZAA==/pansong291.xposed.quickenergy.repair-LkpXGjGjR5QixXexdLLk2Q==/base.apk
[ 2024-03-28T19:11:31.494    10254: 27306: 27306 I/LSPosed-Bridge  ]   Loading class pansong291.xposed.quickenergy.hook.XposedHook
[ 2024-03-28T19:11:32.273    10254: 27619: 27619 I/LSPosed-Bridge  ] Loading legacy module pansong291.xposed.quickenergy.repair from /data/app/~~q_sVbKZ4iv8WJxLTlvvZAA==/pansong291.xposed.quickenergy.repair-LkpXGjGjR5QixXexdLLk2Q==/base.apk
[ 2024-03-28T19:11:32.281    10254: 27619: 27619 I/LSPosed-Bridge  ]   Loading class pansong291.xposed.quickenergy.hook.XposedHook

**Comment by GDZJS** [comment]
![Uploading Screenshot_2024-03-28-19-10-39-510_lockscreen.jpg…]()

**Comment by GDZJS** [comment]
![Uploading Screenshot_2024-03-28-19-10-30-256_lockscreen.jpg…]()

**Comment by GDZJS** [comment]
![Screenshot_2024-03-28-19-10-30-256_lockscreen](https://github.com/HowieHChen/XiaomiHelper/assets/88560651/245e31c9-451e-42dd-8fc5-927e50d65f68)
这是发生错误后

**Comment by GDZJS** [comment]
![Screenshot_2024-03-28-19-10-39-510_lockscreen](https://github.com/HowieHChen/XiaomiHelper/assets/88560651/ea8fddb1-f773-47ab-866d-e7e7cbc3ab25)
会出现系统界面假死
![Screenshot_2024-03-28-19-10-43-326_lockscreen](https://github.com/HowieHChen/XiaomiHelper/assets/88560651/ae763cbe-7f7b-49fa-8b10-bb147486929e)

**Comment by HowieHChen** [comment]
已知

**Comment by GDZJS** [comment]
似乎发现该问题的解决方法:
使用hyperceiler开启优化音乐面板背景混色效果似乎就不会闪退了
![Screenshot_2024-04-03-16-20-36-027_com sevtinge hyperceiler](https://github.com/HowieHChen/XiaomiHelper/assets/88560651/b44e4501-585b-4dca-9639-d9ba7f18f114)

**Comment by HowieHChen** [comment]
已修。不过我这只有旧版安卓复现出SystemUI卡死，你确定新版安卓也存在这个问题吗？

**Comment by GDZJS** [comment]
好的 收到

**Comment by GDZJS** [comment]
目前似乎新版安卓通知已经不会闪退 或者可能是我登记错误 抱歉
