### ISSUE TITLE
两个小建议

### ISSUE THREAD

**Issue by 3508454055** [HowieHChen/XiaomiHelper#14]
1，开启“始终在状态栏中显示时间”之后，锁屏的时候，不显示时间
2，希望增加锁屏时钟显示秒数
![Screenshot_2024-04-26-09-22-05-756_lockscreen-edit](https://github.com/HowieHChen/XiaomiHelper/assets/74099298/e4c2680c-ec92-4aec-b1aa-27f58e3aef2a)

**Comment by HowieHChen** [comment]
第一个弄了，第二个暂时不弄
