### ISSUE TITLE
UI improvement suggestion

### ISSUE THREAD

**Issue by towe96** [HowieHChen/XiaomiHelper#15]
I wanted to modify my battery indicator to only show the percentage without a normal battery symbol.

I found that to be possible when activating the "Swap battery icon and battery percentage" and then selecting "Hide battery icon", as well as having to select the "Percentage (next to the icon)" option in the normal HyperOS UI menu. This worked well, but was a bit unintuitive since "Hide battery icon" also hides the "Swap battery icon and battery percentage" option.

For a future release, I'd therefore love to see a "Only show battery percentage" option which override the stock UIs selection and needs only a single toggle to activate.

Thank you for your work!

Device: Xiaomi 14 EU, HyperOS 1.0.16.0.UNCEUXM

**Comment by HowieHChen** [comment]
Actually "Hide battery icon" will only hide the icon of the battery indicator and not the percentage (if there is one). So just activating this option should be enough to achieve what you want ((you still need to select the "Percentage (next to the icon)" option).

Separate controls for percentages and icons have been added (options in system settings will be ignored).

There will be a “Battery Indicator” dropdown like this:

- Default
- Icon & percentage
- Icon only
- Percentage only
- Hidden
